[package]
name = "linera"
version = "0.1.0"
edition = "2024"

[dependencies]
linera-sdk = "0.10"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
hex = "0.4"
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]